"paragraphUniqueId": 99ddfc02-9d1f-4aff-97f4-0388fda55167
"sourceParagraphId": 487
"sortOrder": 3
"itemType": "Swift-v2_ProductPriceTable"
"header": ""
"template": ""
"colorSchemeId": ""
"moduleSystemName": ""
"moduleSettings": ""
"fields":
  "GlobalRecordPageGuid": "f100774e-2061-484d-aa59-6050df9fc539"
  "Id": "3"
  "ItemInstanceType": ""
  "Layout": "table"
  "Sort": 0
  "Title": ""
"columnId": 1
