"id": e2398c70-4a27-4700-954d-ea1b9216e7a2
"sortOrder": 3
"definitionId": "1ColumnFlex"
"itemType": "Swift-v2_RowFlex"
"container": "Grid"
"containerWidth": 3
"colorSchemeId": "dark"
"topSpacing": 4
"bottomSpacing": 4
"verticalAlignment": "None"
"fields":
  "Id": "94"
  "Sort": 0
  "ItemInstanceType": ""
"columns":
- "id": 1
  "width": 0
