"paragraphUniqueId": 6d69ab62-0d53-4890-b619-06717c15cde3
"sourceParagraphId": 21995
"sortOrder": 1
"itemType": "Swift-v2_Logo"
"header": "Swift"
"template": ""
"colorSchemeId": ""
"moduleSystemName": ""
"moduleSettings": ""
"fields":
  "GlobalRecordPageGuid": "d4981aea-361a-4658-8f73-05d2db7946c2"
  "Id": "172"
  "Image": ""
  "ItemInstanceType": ""
  "Link": ""
  "LogoName": "Swift"
  "LogoWidth": "120"
  "Sort": 0
"columnId": 2
