"paragraphUniqueId": e69bf4fd-294e-4ed2-b03e-48b9ec89f581
"sourceParagraphId": 22033
"sortOrder": 1
"itemType": "Swift-v2_Text"
"header": "Set your password"
"template": ""
"colorSchemeId": ""
"moduleSystemName": ""
"moduleSettings": ""
"fields":
  "GlobalRecordPageGuid": "8feb93ea-e47c-4192-b36e-6bb047dc63dd"
  "Id": "1408"
  "ItemInstanceType": ""
  "Sort": 0
  "Subtitle": ""
  "Text": ""
  "Title": "<h2 class=\"dw-h2\">Set your password</h2>"
"columnId": 1
