"paragraphUniqueId": 8339a2a5-4254-40cc-b94c-cef786555f76
"sourceParagraphId": 22015
"sortOrder": 3
"itemType": "Swift-v2_ProductShortDescription"
"header": "Short description"
"template": ""
"colorSchemeId": ""
"moduleSystemName": ""
"moduleSettings": ""
"fields":
  "GlobalRecordPageGuid": "56b34106-1f7b-45de-b316-a119ccce9d59"
  "Id": "41"
  "ItemInstanceType": ""
  "Sort": 0
  "Title": "Short description"
"columnId": 1
